### ISSUE TITLE
Sorting in-Raid sometimes weird

### ISSUE THREAD

**Issue by ViP3R76** [DrakiaXYZ/SPT-QuestTracker#2]
Hey, sometimes if you are in-Raid and use the sorting function. The actual map is not always ordered to top of the list.
Sorting seems to be offguard a little :-)

**Comment by DrakiaXYZ** [comment]
This is caused by BSGs new sorting, not Quest Tracker. 

All Quest Tracker does is prioritize tracked quests over non-tracked quests when sorting by the Status column (So a non-tracked quest for the current map will show below _all_ tracked quests, including those for other maps)
